name: Deploy (self-hosted)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Executar Script de Deploy Local
        run: |
          /var/www/deploy.sh